import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    containerLogin: {
        padding: 20,
        backgroundColor: "red",
        flex: 1,
    },
    containerRegister: {
        padding: 20,
        backgroundColor: "#5b9f91",
        flex: 1,
    },
    title: {
        fontSize: 28,
        marginBottom: 20,
        color: "#00ff00",
        fontWeight: "bold",
        textAlign: "center",
    },
    titleLogin: {
        fontSize: 60,
        fontWeight: "bold",
        textAlign: "center",
        color: "rgba(255, 0, 0, 0.7)",
        textShadowColor: "#00ff00",
        textShadowOffset: { width: -2, height: 2 },
        textShadowRadius: 5,
    },
    label: {
        marginTop: 10,
        marginBottom: 5,
        color: "orange",
        fontWeight: "bold",
    },
    inputLogin: {
        borderWidth: 2,
        borderColor: "green",
        borderRadius: 10,
        padding: 12,
        marginBottom: 10,
        backgroundColor: "white",
        color: "red",
        fontWeight: "bold",
    },
    inputRegister: {
        borderWidth: 2,
        borderColor: "lime",
        borderRadius: 12,
        padding: 12,
        marginBottom: 10,
        backgroundColor: "white",
        color: "black",
        // shadowColor: "#ff0000",
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 1,
        shadowRadius: 4,
    },
    registerButton: {
        backgroundColor: "#ff0000",
        paddingVertical: 18,
        paddingHorizontal: 25,
        marginTop: 30,
        borderRadius: 8,
        alignItems: "center",
        shadowColor: "#00ff00",
        shadowOpacity: 1,
        shadowOffset: { width: 2, height: 2 },
        shadowRadius: 6,
        elevation: 5,
    },
    loginButton: {
        backgroundColor: "#aaa",
        padding: 15,
        marginTop: 30,
        borderRadius: 15,
        alignItems: "center",
    },
    buttonText: {
        fontSize: 40,
        fontWeight: "bold",
        color: "#00ff00",
        textShadowColor: "#ff0000",
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 1,
    },
    toggleContainer: {
        flexDirection: "row",
        marginTop: 30,
        justifyContent: "center",
    },
    toggleText: {
        color: "red",
        paddingLeft: 5,
        fontWeight: "bold",
        textDecorationLine: "underline",
    },
    toggleTextWhite: {
        color: "white",
    },
    error: {
        marginTop: 10,
        color: "#ff0000",
        fontWeight: "bold",
        fontSize: 16,
        backgroundColor: "#ffeeee",
        padding: 10,
        borderRadius: 5,
        borderColor: "red",
        borderWidth: 1,
    },
    disabledButton: {
        backgroundColor: "#555",
        opacity: 0.6,
    },
});

export default styles;